novalnet_sylius_shop:
    resource: "@NovalnetSyliusNovalnetPaymentPlugin/Resources/config/routing/shop_rounting.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$